name: "Test cosign"

on:
  pull_request_target:
    types:
      - opened
      - synchronized
      - edited
      - labeled
      - unlabeled
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      DOCKER_REPO: riccardofadda/test-cosign
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cosign
        if: github.event_name != 'pull_request' && github.event_name != 'pull_request_target'
        uses: sigstore/cosign-installer@v3.1.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_REPO }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: riccardofadda
          password: provalogindocker

      - name: Build and push Docker image
        if: github.event_name != 'pull_request' && github.event_name != 'pull_request_target'
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          
      - name: Sign the image
        if: github.event_name != 'pull_request' && github.event_name != 'pull_request_target'
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: cosign sign --yes ${{ env.DOCKER_REPO }}@${DIGEST}

  cosign-verification:
    name: Cosign Verification
    runs-on: ubuntu-latest
    env:
      TAGS: ${{ needs.build-and-push.outputs.tags }}
      WORKFLOW_REF: ${{ github.workflow_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Cosign verification for each pushed tag
        env:
          TAGS: ${{ needs.build-and-push.outputs.tags }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
        run: |
          for tag in $TAGS; do
            echo
            echo "Verifying the '$tag' tag with Certificate Identity: 'https://github.com/${WORKFLOW_REF} and Certificate OIDC Issuer: 'https://token.actions.githubusercontent.com'"
            echo
            cosign verify "$tag" --certificate-identity="https://github.com/${WORKFLOW_REF}" --certificate-oidc-issuer="https://token.actions.githubusercontent.com" | jq .
            echo
          done
          echo "To verify a tag with cosign, launch the command:"
          echo "cosign verify [REPOSITORY]:[TAG] --certificate-identity=[CERTIFICATE_IDENTITY] --certificate-oidc-issuer=[CERTIFICATE_OIDC_ISSUER]"